language: c
sudo: false

env:
        matrix:
                - TEST=eduos_shell
                - TEST=host_shell
                - TEST=time
                - TEST=mutex
                - TEST=cat

script : ./test/run.sh -v $TEST
